### PR TITLE
Update convert_gt_xml.py

### PR DESCRIPTION
**Pull request by leyuan**
Fix the inconsistent type when writing the text file.

For this error:
image

### CODE REVIEW

**Comment by Cartucho** [comment]
Thanks! The thing is that I wanted to address this issue https://github.com/Cartucho/mAP/issues/38.
Apparently, some values from the XML format can be `floats`, therefore we need to convert them to `int`.

We can solve this by changing that line of code to:
`       new_f.write(obj_name + " %d %d %d %d\n" % (float(left), float(top), float(right), float(bottom))) `

This way we first convert the `string of float/int` to `string of int`.

**Comment by Cartucho** [comment]
Another possibility is to treat this as only strings:
`new_f.write("%s %s %s %s %s\n" % (obj_name, left, top, right, bottom))`

And then do the parsing to int in the `main.py`.

Which one do you think it is best?

**Comment by leyuan** [comment]
Thanks, @Cartucho. For calculating the mAP, does it require everything to be integers? If we can just write the float as strings, then we do not need to parse them back and forth, thus the second one :) Let me know, and I will change my pr.

**Comment by Cartucho** [comment]
I agree with you, let's do it with the second one.

**Comment by leyuan** [comment]
Thanks. Please take a look :)

**Pull request merged**
