### PR TITLE
Add remove_space.py script

### PR DESCRIPTION
**Pull request by off99555**
This script is designed to be used instead of `rename_class.py` when there are a lot of classes with spaces.
Because running `rename_class.py` with lots of classes would be tedious.
E.g. if we have classes like this:
```
license plate
0 zero
1 one
2 two
```
We would only need to run `remove_space.py` once to replace spaces with delimiter like so:
```
license-plate
0-zero
1-one
2-two
```
And of course, the delimiter is adjustable.

### CODE REVIEW

**Comment by Cartucho** [comment]
Looks great! Thanks!

**Comment by MattiasM80** [comment]
Hi,
Why not simply use ; as a delimiter all through the code rather than enforcing the renaming of classes?
split() is used throughout the code and if called with an argument, e.g. split(';'),  class names could be preserved and the rest of the code would work as usual, wouldn't it?

**Comment by Cartucho** [comment]
@MattiasM80 Yes, you are right.

Even better would be to use a `.json` structure like [darkflow](https://github.com/thtrieu/darkflow):
`[{"label":"person", "confidence": 0.56, "topleft": {"x": 184, "y": 101}, "bottomright": {"x": 274, "y": 382}},
{"label": "dog", "confidence": 0.32, "topleft": {"x": 71, "y": 263}, "bottomright": {"x": 193, "y": 353}},
{"label": "horse", "confidence": 0.76, "topleft": {"x": 412, "y": 109}, "bottomright": {"x": 592,"y": 337}}]`

With this, we could remove many lines of code and make it more robust.

**Comment by off99555** [comment]
You have to make sure that it is consistent with darkflow.

**Comment by Cartucho** [comment]
Yeah, if it was consistent it would make life easier to the darkflow users.
I will consider doing this for a future release.

**Pull request merged**
