### PR TITLE
Add extra script "intersect-gt-and-pred.py"

### PR DESCRIPTION
**Pull request by off99555**
This pull request does these things:
1) Fix the previous bug of PR #18, (forget to commit `bypass` function)
2) Add script `intersect-gt-and-pred.py` used to fix file not found error by moving non-intersected ground-truth and predicted files into a backup folder.
3) Write README for this script and more info to the error message in `main.py`

### CODE REVIEW

**Comment by off99555** [comment]
Example output of the script:
```
total ground-truth files: 863
total predicted files: 946

No backup required for ../ground-truth
total ground-truth backup files: 0
total predicted backup files: 83
total intersected files: 863
Intersection completed!
```

**Comment by Cartucho** [comment]
Yeah, this makes it a lot easier when there are a lot of files!

What do you think of renaming `backup2` to something like `backup_matching_file_not_found`? It would make things more clear.

**Comment by Cartucho** [comment]
One last thing, we should mention something in the `main.py` code, no?
So that people use your code when they get file not found. 

Both in line 301 and 378, I would suggest something like:

`error_msg = "Error. File not found: predicted/" + file_id + ".txt\n"`
`error_msg += "(You can avoid this error message by running extra/intersect-gt-and-pred.py)"`

**Comment by Cartucho** [comment]
Oh you already did that! My bad!

**Comment by off99555** [comment]
I will change it to your message.

**Comment by off99555** [comment]
Deal?

**Comment by Cartucho** [comment]
Looks great! Thank you!

**Pull request merged**
