### PR TITLE
Fix convert_yolo_pred allow negative bbox values

### PR DESCRIPTION
**Pull request by timlueg**

### CODE REVIEW

**Comment by Cartucho** [comment]
Thanks! Can YOLO really predict bounding boxes with negative coordinates?

**Comment by timlueg** [comment]
Mine did (yov3-tiny). I looked at some of these images and they show objects that are close or cut off at the boundaries of the image. I think it has to do with the bbox conversion the detector script does or the size of the predefined anchor boxes.

**Comment by Cartucho** [comment]
Yeah, it could also be related to having the input image with the wrong dimensions. I'm not sure but I think you had to use something like multiple of 32.

Anyway does the rest of the code (calculating the mAP score) work, even with negative numbers? Or do you think we should zero the values when negative? I just wanted to make sure this won't create conflicts in the future.

**Comment by timlueg** [comment]
Yes the rest of the code works. The calculations also seem to be correct but i didn't compare them yet.

I don't think it's because of the input image dimensions. I tried multiple cops with one of these images where the object is ~90% inside the image. This Always results in a negative top_y position.

I think yolo predicts bbox center_x, bbox_center_y, width, height. The converted detector.c values (lleft_x, top_y) can therefore be outside of the images when the predicted width or height are large enough and/or the bbox center is close to the boundaries of the image.

I looks like when darknet draws the images [it clamps them](https://github.com/pjreddie/darknet/blob/680d3bde1924c8ee2d1c1dea54d3e56a05ca9a26/src/image.c#L288) at 0 or the image width/height. So it seems negative values are expected outputs.
 I don't think we should modify/zero the predictions the network supplies.

**Comment by Cartucho** [comment]
Yeah, you are right, I remember now that they zero the values when drawing.
Ok, perfect! I will merge it then!

**Pull request merged**
